apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgCV8jpY142Xs2yhJ93MEBpm1VhB1KN+q17jHp0dgEgu+Ml81WpqSo6Ke2pa4wZmYfjPu0+g39JGK9gzB+jKbGKsHW2hxn7jcf8hMqto41whYjvjLzUBjkSK9XKCHKTi6w1w2GCQ5meb0L+Nx4woUiA5KT5l748fsN+7P2Mv/ojPHDzW8OmwA3X+VP1ow+DRjKUui9OrruSmYQYlODQH0Ib02ftxxyaGM8OvQNVk4HW/g0QVsHW8BtFoNPcdTtI62wZFXecMrblk07+j/GVN9GrYEWvcclFIA0WVTRb3oFLd8h+G7gdXx9xJFFwt8zcJZyVBQ0JccyYCvfRrmfTDCmWAzBuElSpANirJLCF6YzM47uRVlnH1QHehePN0YL9B/pJs4C1UAfn/c5HgQZ+hPjVAa3WiWCRvCkri6zvBH76U6HCyKpF040m9M8XuW9ONhc4Auzr/GkVpqbOutBrSUwDqWPU3mJgn05NiLECE22ZdecKp569biXZXUgq4pADI4khyGxvBhl7tsqFMuw8jkgVpEJqNizCRC7e4hK0YxHC4SeaBglT0hFGv6JHmb4lYp4dmCf2uYFyDpba5HzAd9sjExTECGV44tvpew7ifV3oT804gb2sCFYd8kSa9tCsd4b0nPXAFWEQagKifD+9QX1z4GdFkHFkti2p250+L2LYV6DyJZRxKwyIil2zGzX5vnKoK+eosDhdj7yTrzt0sQAESgZosfbJcRz+uAoSfC7mA1TqDIMLm8T8A
    username: AgCIwWK2o5v3BUiCeILA8OKUpNPlpdXI2H12XT5mc15AxSgGM3SnqB/SvMU9sF0hoU7Izqar4osb9tSa8NaRVohZ02vy3Gh0f+BidW9XVN0Hhfn4k/BIdoyy5dm0d/bv+rJ78QVmhjDQHI0LFNTsLqukVZKi7gq0RI4zCJ2+Lwaeuaqi5Z1OuJdRsylylR9gb96yPwyiI4/N0cLyAMQPca81w/+HBRXtkLw9B27cpsEhcyRlTJE3Ulbx011wAABy78T7aOCQfWizprnapZ/YBLYcrfo3GIbuFnwdQvWciULT0Rgh8AZjP6V1LFiELcOwY2gTchR4yBLk8D73e3XEXIAZnyk+Y6NvuhDvYkHT4i9mpcyGA9XmLFotOntnAi51Ceb4sK5VWh4UvsttvOEZw4VFUqz/VLbQoqCE+1wth3iBW0gcjL74I0L0bbMfMtgH+/zaFN4Xo8XYVaWWMuZEfaMzW5bm/eeH2PVxvFh1cWyT0y/vyBuSNQN+kVehFiJHnwVuqtaYf3r5r79rigncD10vN6vqKfBB4nZJDF5sQKzUTMUHEeURtoGinB8gIjid1Oi/ZuW9rGiao97bWMe0kEO9NWjushY8zsePfYtmym8h6AmkpOqrAAzpWoysNJlluDv/E9eVVdTKVcArntfIausC4b1VumJE47/c4oiIRURBMC1FxfdbSpXonXbTChvGrryMZa37pwkBLPAUuS9M4WYDsCqP1ADKI04=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

