apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgBlmRfY29q7ldeWJubf2Q3FK+McshBvlssPjLEskBN4n+q3KqvBI4lq0j9bH32USIUYN0Faa0TGNtVB2XIQalB+/WKUQRQgNqQAugAuBUT0sH4ESvkv7gOpV/wMMHjEJu5vSUdtdhXyGwE7LgEhVsvTYwayWsUM+rLmF6UJZscwO601l54iq8Lu6L+NHb+VuzkHmFVFIzDATuNHMIVnxxCUAR1jjrum+W7708UP7NeOKIHkaWDXPsfgL9CtyAMeaNbanGA9We2srhyiHnBrabVDvaTqxsZhCTO4wBJuHk8S5mkCawyU3d37o4tgBHbQN9TrluWTBsv4BlW8574FkaHeirmurxhtFoTqDHDOlkiATEO1wxbbeChpH1xBPjcMwiB8Yz/RsWREq++tr0IPVRW096CmVB1TZ20W79lPSeVvhg+gDgEdaSaZAEea3Jd+xhBvHqOxlOiu+sb2vyWy4OmQ1fDkfYTFUxrnGcpGQGXIAhgFxFFc4doYhM7Vmq/QTay2naq6fcMQWwbLC9MWtw6quJ9hKFjDmuNQLM5cmWiujN8BN5Rpidh9URKIhC1Wdh5f0u95O86XdLFYbGSpxNLcqSOz1YF260yqyAIIVfrgTghZYJC0cFJkH62GuSUdHJtBOzjMxcm79tDNkoix2YLZCK5zyj6kxNj6qxrGd85GIs4lp8s2wdqqWftzj78PIciVOSP8INUnKJffuzXOG/yi5JerXqMV3I7F4Y87qFAL3rA77OLI11uR
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

