resources:
- hooks/post-sync.yaml
- secrets/basic-auth-rest-secret.yaml
- secrets/ibm-ace-server-jks-secret.yaml
- secrets/ibm-ca-jks-secret.yaml
- secrets/ibm-client-key-certs-secret.yaml
- secrets/ibm-rest-dbparms-secret.yaml
