kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ace-bar-webhook-event-listener
spec:
  to:
    kind: Service
    name: el-ace-bar
  port:
    targetPort: https-listener
  tls:
    termination: passthrough
  wildcardPolicy: None

