apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin.registrykey
  namespace: openshift-operators
spec:
  encryptedData:
    .dockerconfigjson: AgAPJbDQz+Qj3OgOrDseGLdWFfge/ANTD15makqsa5+rz0+2bnYCsIbinQq8LweT5tTJSC9KnIFm5Q5Gn4tRcEwM+5GMoFH8v+lNQX/UOAzI40zN0v1ygj7E2d2uROXL8bTUwbyQvAaLs7rIH21IJPBT/YqutNoAQulzW+ux2pBhRoYORgEKLkDkRc+c15XvF02z5VeN+QFgOaWjRi+ZUZ9VF/qqt92QzizdFXFOBU14nlXuDsd7OEwaYdzyqPtnv9OlAKh8wyCrIIZwSH1nYyKDk/vvM0hTfEeK3k4YTd6ANLptdwLVMln2b7dyl5QWhPZbno7EQKhFVnYoQ8x6CGHw16mfLR4vltg0jix+05WDCuFlI756cbmZ6EVKOMb0YEM0YS/JJovEXDClVAG1nKlY8PWvoj62G4t8TxUL5ByeBCbXxvAoILlkzCdyO0Mc2SJXQmz+pNymmEGby6re/EMup9G2rzjpe+AvWzHNNfj6To14cxvgYERAYXZ+DkCy8pvndl1nlBKVse7u/dr4Ib3wpMpezeHRS5AWBZwNv6jUBOhPBbmah6G/nIZWgXSzXJ5E66iGrqBRPAIslQL0S6QFaySVRI1zII3JIh4BmGpAxIXXbZYT52NpXuGLHUZ6T0vlrxxZ1rF8mzq23WZakFQDlLg/UMgYRa8dMJWoYnxOsidMvxZiuHHIGRRjp4BUMGhFBdc9Kyt0YD3QlaJ5aF0NiE7G6FH0jAhHLRl8jQeWp3fL3UEoGL+/P6amtrvcXxwqRcswbFysu/xtzzypxYZwgXhsxPR6y2BXgfx8x1yIfSzTku10L58zIsbz1Ac1olXdT7cDVl4zu7rWFSgSbprz5HpPCyDj9Wh7rSUuSIbUJDGUfv4qenWePCnCDHzy+fbX3EuIJlMUTcvrZfXzl5HDqo5i+lOkpDmslCUY5PHHhMfpmga555FOINotgieZl4bbQ6I61dibBJKrBiXChm0Mp+aIOXVm/IGyhKKBsMr0L5ZKjg5LrvCz1uH0JymJf/jqqCyuMIFIB75txV90nZ+CGfH+0OH6p8In0R3G9lZXiAHV7WHoj6d/AyL74hL0sMxVHxlk94pKDSz8qQ2iVtypVsi6gfsy5CL6EIlaMTuO5WevCAK//vYd5M3vEhtT+BoMwyzOZUGKcQRSIPvCBp+xR7TyugEzrtfA0yZH9JX6S5wu+KdfLmqeZrKZBKHf+w/FKw9eaYxA/pj8cVmSiew2j+rKQ0qBsxxEZxUygLwf2rYTFJW9igCutlUYfZq4AWnykNyio9mfp+QCcOU5jsHY80Bmhd5i0ce6dQzRv4NdK9R5L8eOQgrwWVKhOQkMZKCG
  template:
    metadata:
      creationTimestamp: null
      name: admin.registrykey
      namespace: openshift-operators
    type: kubernetes.io/dockerconfigjson

