kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-pipelines-rolebinding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:ci'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-pipelines-clusterrole
